# Problem 1

In [4]:

# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.linspace(0, 10, 5)
print(matris)
# 3 - matris'in boyutunu öğrenin
print(matris.shape)

# 4 - matris'i yeniden boyutlandırın
matris = matris.reshape(5,1)
print(matris)
# 5 - matris'in boyut sayısını öğrenin
print(matris.ndim)

[ 0.   2.5  5.   7.5 10. ]
(5,)
[[ 0. ]
 [ 2.5]
 [ 5. ]
 [ 7.5]
 [10. ]]
2


# Problem 2

In [11]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris = np.arange(1, 10, 2)
print(matris)
# 2 - Oluşturduğunuz matrisi parçalayın
split_matris = np.split(matris, [2])
print(split_matris)

# 3 - Parçalanmış matrisleri birleştirin
concatenated_matris = np.concatenate(split_matris)
print(concatenated_matris)

[1 3 5 7 9]
[array([1, 3]), array([5, 7, 9])]
[1 3 5 7 9]


# Problem 3

In [10]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
matris = np.random.choice(np.arange(5, 101, 2), size=10)
print(matris)
# 2 - matris'in özelliklerini inceleyin
print("Shape:", matris.shape)
print("Size:", matris.size)
print("Data type:", matris.dtype)


[33 97 33 49 87 47 65  9 71  9]
Shape: (10,)
Size: 10
Data type: int32
