# Problem 1 

In [2]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
array =  np.array([15,45,75,85,10])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
kücükten_büyüge = np.sort(array)
print(kücükten_büyüge)

[10 15 45 75 85]


# Problem 2

In [3]:
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
result = np.array([10,15,30,45,60])
print(result)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
result2 = np.arange(5,15)
print(result2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
result3 = np.arange(50,100,5)
print(result3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
result4 = np.zeros(10)
print(result4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
result5 = np.ones(10)
print(result5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
result6 = np.linspace(0,100,5)
print(result6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
result7 = np.random.randint(10,30,5)
print(result7)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
result8 = np.random.randn(10)
print(result8)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matris = np.random.randint(10,50,15).reshape(3,5)
print(matris)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
matris = np.random.randint(-50,50,15).reshape(3,5)
print(matris)

rowTotal = matris.sum(axis = 1)
colTotal = matris.sum(axis = 0)
print(matris)
print(rowTotal)
print(colTotal)
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(matris.max())
print(matris.min())
print(matris.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(matris.argmax())
print(matris.argmin())

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
arr = np.arange(10,20)
print(arr)

print(arr[:3])


# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(arr[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.

print(matris[0])
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?

print(matris[1,2])
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.

print(matris[:,0])
# 18- Üretilen matrisin her bir elemanının karesini alınız.

print(matris ** 2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
random_numbers5 = np.random.randint(-50 , 50 , size=(3,5))

print((random_numbers5 > 0) & (random_numbers5 % 2== 0))

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[13 19 12 20 23]
[-0.16614435 -0.44048577  0.07788612 -0.2120456  -1.11530448 -0.72926314
 -0.69814072 -0.385927   -0.30330592  1.8339672 ]
[[12 28 39 35 13]
 [27 38 33 41 23]
 [16 32 11 24 34]]
[[-11 -26  -2   0  12]
 [-32 -17 -28  39 -25]
 [ -5 -11  30 -23 -18]]
[[-11 -26  -2   0  12]
 [-32 -17 -28  39 -25]
 [ -5 -11  30 -23 -18]]
[-27 -63 -27]
[-48 -54   0  16 -31]
39
-32
-7.8
8
5
[10 11 12 13 14 15 16 17 18 19]
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[-11 -26  -2   0  12]
-28
[-11 -32  -5]
[[ 121  676    4    0  144]
 [1024  289  784 1521  625]
 [  25  121  900  529  324]]
[[False False False False False]
 [ True False False  True  True]
 [False False False False  True]]
